{"name": "test_pilot_food_pricing", "status": "broken", "statusDetails": {"message": "pyodbc.Error: ('HY090', '[HY090] [Microsoft][ODBC Driver Manager] Invalid string or buffer length (0) (SQLExecDirectW)')", "trace": "request = <FixtureRequest for <Function test_pilot_food_pricing>>, _pytest_bdd_example = {}\n\n    @pytest.mark.usefixtures(*func_args)\n    def scenario_wrapper(request: FixtureRequest, _pytest_bdd_example: dict[str, str]) -> Any:\n        scenario = templated_scenario.render(_pytest_bdd_example)\n>       _execute_scenario(feature, scenario, request)\n\n..\\..\\..\\..\\scoop\\apps\\python\\current\\lib\\site-packages\\pytest_bdd\\scenario.py:187: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n..\\..\\..\\..\\scoop\\apps\\python\\current\\lib\\site-packages\\pytest_bdd\\scenario.py:157: in _execute_scenario\n    _execute_step_function(request, scenario, step, step_func)\n..\\..\\..\\..\\scoop\\apps\\python\\current\\lib\\site-packages\\pytest_bdd\\scenario.py:127: in _execute_step_function\n    return_value = call_fixture_func(fixturefunc=step_func, request=request, kwargs=kwargs)\n..\\..\\..\\..\\scoop\\apps\\python\\current\\lib\\site-packages\\_pytest\\fixtures.py:890: in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfixed_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f68a446cebf13ad08a80b60fa9c039a3\")>\n\n    @given('The User Receives The Result Set', target_fixture=\"02_validate_data_test\")\n    def receive_result_set(fixed_driver):\n        \"\"\"The User Receives The Query Results\"\"\"\n        global query_element\n    \n>       cursor.execute(query_string_value)\nE       pyodbc.Error: ('HY090', '[HY090] [Microsoft][ODBC Driver Manager] Invalid string or buffer length (0) (SQLExecDirectW)')\n\nTest_Steps\\test_02_pilot_food_pricing.py:35: Error"}, "description": "../Features/02_Pilot_Food_Pricing.feature: Scenario to Validate the Data Test", "start": 1673289590720, "stop": 1673289590731, "uuid": "c9c4cef3-b244-4f14-96c8-05054e6e0fb1", "historyId": "ca9d189fe10adbdcd99593c93d1614b3", "testCaseId": "1058462fdae6c3efec784c3a5ec78b62", "fullName": "Test_Steps.test_02_pilot_food_pricing#test_pilot_food_pricing", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('fixed_driver')"}, {"name": "parentSuite", "value": "Test_Steps"}, {"name": "suite", "value": "test_02_pilot_food_pricing"}, {"name": "host", "value": "EC2AMAZ-O7K498H"}, {"name": "thread", "value": "10496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Steps.test_02_pilot_food_pricing"}]}